name: tekartik_cmd_record
description: Record command line process stdout, stderr and stdin
version: 0.3.0
homepage: https://github.com/tekartik/cmd_record.dart

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  process_run: '>=0.10.9-dev.1'
  tekartik_cmd_echo:
    git:
      url: git://github.com/tekartik/cmd_echo.dart
      ref: null_safety
    version: '>=0.2.1+1'

dev_dependencies:
  test: ">=1.0.0"
  dev_test: any

# dependency_overrides:
#  process_run:
#    git: https://github.com/tekartik/process_run.dart
#    version: ">=0.5.4"
#    path: ../process_run.dart
executables:
  cmd_record: