name: tekartik_cmd_record
description: Record command line process stdout, stderr and stdin
version: 0.1.0
homepage: https://github.com/tekartik/cmd_record.dart
author: tekartik <alex@tekartik.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  process_run: '>=0.5.2'
  tekartik_cmd_echo:
    git: git://github.com/tekartik/cmd_echo.dart

dev_dependencies:
  test: ">=0.12.0"
  dev_test: any

dependency_overrides:
  process_run:
    git: git://github.com/tekartik/process_run.dart
#    path: ../process_run.dart
executables:
  cmd_record: