name: tekartik_cmd_record
description: Record command line process stdout, stderr and stdin
version: 0.2.2
homepage: https://github.com/tekartik/cmd_record.dart
author: tekartik <alex@tekartik.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  process_run: '>=0.10.2'
  tekartik_cmd_echo:
    git:
      url: git://github.com/tekartik/cmd_echo.dart
      ref: dart2
    version: '>=0.2.1+1'

dev_dependencies:
  test: ">=1.0.0"
  dev_test: any

# dependency_overrides:
#  process_run:
#    git: git://github.com/tekartik/process_run.dart
#    version: ">=0.5.4"
#    path: ../process_run.dart
executables:
  cmd_record: